-- U1/U4 向け Supabase テーブル作成SQL
-- SupabaseのSQLエディタで実行してください

CREATE TABLE IF NOT EXISTS public.oracle_clicks (
    id bigint generated by default as identity primary key,
    label text not null, -- 'line_cta', 'vernier_cta', 'x_share', 'line_share'
    src text not null,   -- 流入元 ('direct', 'share', 'fortune_today' etc)
    ua text,             -- ユーザーエージェント（一部）
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 検索用のインデックス
CREATE INDEX IF NOT EXISTS idx_oracle_clicks_created_at ON public.oracle_clicks(created_at);
CREATE INDEX IF NOT EXISTS idx_oracle_clicks_label ON public.oracle_clicks(label);
