-- ============================================================
-- 開運オラクル クリック計測テーブル（2026-08-31 版）
-- SupabaseのSQLエディタに貼り付けて「Run」するだけ。
--
-- ★なぜ作り直したか
--   旧 setup_supabase.sql は列が (label, src, ua) だけで、
--   しかも label と src が NOT NULL だった。
--   ところが 2026-08-30 に追加した app/api/track/route.ts は
--   (event, src, path, meta) を書き込む。
--   → 旧SQLのままだと、ヴェルニ導線のクリック計測は
--     「列が存在しない」「NOT NULL違反」で必ず失敗する。
--   2026-08-31 に実コードを読んで両方の書き込み元に合わせた。
--
-- ★書き込み元（2026-08-31 実測）
--   app/api/track/route.ts : insert({ event, src, path, meta })
--       event は 'page_view' / 'line_cta_click' / 'verni_cta_click'
--                / 'share_click' / 'share_open' のいずれか
--   app/api/click/route.ts : insert({ label, src, ua })
--
-- ★読み出し元
--   app/api/funnel-report/route.ts   : select('label, src, created_at')
--   app/api/health/tracking/route.ts : count のみ
--
-- ★NOT NULL を付けないこと
--   track/route.ts の src / path は入力が空だと null を渡す実装
--   （clip() が null を返す）。NOT NULL にすると計測がまた黙って落ちる。
-- ============================================================

CREATE TABLE IF NOT EXISTS public.oracle_clicks (
    id          bigint generated by default as identity primary key,

    -- track/route.ts 用
    event       text,          -- 例: 'verni_cta_click'
    path        text,          -- 押された画面のパス
    meta        jsonb default '{}'::jsonb,

    -- click/route.ts 用（旧経路。残す）
    label       text,          -- 例: 'line_cta', 'vernier_cta'
    ua          text,          -- User-Agent の先頭200文字

    -- 両方で使う
    src         text,          -- 流入元 'direct' / 'share' など

    created_at  timestamp with time zone
                default timezone('utc'::text, now()) not null
);

-- 集計用のインデックス
CREATE INDEX IF NOT EXISTS idx_oracle_clicks_created_at ON public.oracle_clicks(created_at);
CREATE INDEX IF NOT EXISTS idx_oracle_clicks_event      ON public.oracle_clicks(event);
CREATE INDEX IF NOT EXISTS idx_oracle_clicks_label      ON public.oracle_clicks(label);

-- ★既に旧スキーマのテーブルがある場合の救済（新規作成なら何も起きない）
ALTER TABLE public.oracle_clicks ADD COLUMN IF NOT EXISTS event text;
ALTER TABLE public.oracle_clicks ADD COLUMN IF NOT EXISTS path  text;
ALTER TABLE public.oracle_clicks ADD COLUMN IF NOT EXISTS meta  jsonb default '{}'::jsonb;
ALTER TABLE public.oracle_clicks ALTER COLUMN label DROP NOT NULL;
ALTER TABLE public.oracle_clicks ALTER COLUMN src   DROP NOT NULL;

-- ============================================================
-- RLS（行レベルセキュリティ）
--
-- ★2026-08-31 実測: 新しいプロジェクトでは RLS が有効になっており、
--   anonキーからの INSERT が拒否された。
--   実際のエラー:
--     42501 / new row violates row-level security policy for table "oracle_clicks"
--   SELECT は通るのに INSERT だけ落ちるため、
--   「疎通OK」だけ見ていると気づけない。必ず書き込みまで試すこと。
--
-- クリック計測は「誰でも書ける・集計のために読める」必要があるので
-- ポリシーを明示的に作る。
-- ============================================================

ALTER TABLE public.oracle_clicks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon can insert clicks" ON public.oracle_clicks;
CREATE POLICY "anon can insert clicks"
    ON public.oracle_clicks
    FOR INSERT TO anon
    WITH CHECK (true);

DROP POLICY IF EXISTS "anon can read clicks" ON public.oracle_clicks;
CREATE POLICY "anon can read clicks"
    ON public.oracle_clicks
    FOR SELECT TO anon
    USING (true);

-- ★注意: SELECT を anon に開けているのは、集計API
--   app/api/funnel-report/route.ts が anonキーで読んでいるため。
--   anonキーはブラウザに配られる公開鍵なので、
--   この設定では「クリック履歴(UA含む)が公開鍵で読める」状態になる。
--   個人を特定する情報は入れていないが、気になるなら
--   funnel-report を service_role キーに切り替えたうえで
--   上の SELECT ポリシーを削除すること（別作業）。

-- ============================================================
-- 確認用（任意）: これを実行して 0 行が返ればテーブルは出来ている
-- SELECT count(*) FROM public.oracle_clicks;
-- ============================================================
